pipeline{
  //prebuild stage
    agent{
        label "TEST-NODE"
    }
     parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev', 'stage', 'prod'], description: 'Select environment')
     }
    // stages
    stages{
        stage('Build'){
            steps{
                echo "Building Stage"
                echo " please select your choice ${params.ENVIRONMENT} "
            }
        }
        stage('Deploying'){
            steps{
                echo "Deploying Stage"
            }
        }
        stage('Scanning stage '){
            steps{
                echo "Scanning stage"
            }
        }
        stage('testing stage'){
            steps{
                echo "Testing stage"
            }
        }
        stage('Deploy to Prod') {
    when {
        expression { params.ENVIRONMENT == 'prod' }
    }
    steps {
        echo "Deploying to production"
    }
    }
    }

    post{
        always{
            echo "i will print always bro"
        }
        success{
            echo "your build was success"
        }
        failure
        {
            echo " your build was failure"
        }
    }

}