pipeline{
  //prebuild stage
    agent{
        label "TEST-NODE"
    }
    environment{

    }
    // stages
    stages{
        stage('Build'){
            steps{
                echo "Building Stage"
            }
        }
        stage('Deploying'){
            steps{
                echo "Deploying Stage"
            }
        }
        stage('Scanning stage '){
            steps{
                echo "Scanning stage"
            }
        }
        stage('testing stage'){
            steps{
                echo "Testing stage"
            }
        }
    }

    post{
        always{
            echo "i will print always bro"
        }
        success{
            echo "your build was success"
        }
        failure
        {
            echo " your build was failure"
        }
    }

}