pipeline {
    agent {
    label "AGENT-1"
    }
    stages{
        stage('Build'){
            steps {
                echo "This statement from the build stage"
            }
        }
        stage('Tesing'){
            steps{
                echo "This statement from the Testing"
            }
        }
        stage('Deploy'){
            steps{
                echo "This is from Deploying"
            }
        }
    }
    post{
        always{
            echo "You have run the pipeline"
        }
        success{
            echo "Your pipeline was success"
        }
        failure{
            echo "Your pipeline was failure"
        }
    }
}