pipeline {
    agent any
    environment{
        Course = "Jenkins"
    }
    //build
    stages{
        stage('Build'){
            steps{
            echo "Building......!"
            }
        }
        stage('Deploy'){
            steps{
                echo "Deploying....!"
            }
        }
        stage('Test'){
            steps{
                echo "Testing....!"
                echo "Course name is: ${env.Course}"
                sh 'env | sort'
            }
        }
    }

    // post 
    post{
        always {
            echo "it is running if you got success means it is working else it is not working"
        }
        success {
            echo "it is working bro...!"
            
        }
        failure {
            echo "it is not working...!"
        }
    }

}
