pipeline {
    agent {
        label "roboshop-agent"
    }
    environment{
        Course = "Jenkins"
    }

    options{
        timeout
    }
    //build
    stages{
        stage('Build'){
            steps{
            echo "Building......!"
            }
        }
        stage('Deploy'){
            steps{
                echo "Deploying....!"
            }
        }
        stage('Test'){
            steps{
                echo "Testing....!"
                echo "Course name is: ${env.Course}"
            }
        }
        stage('Approval') {
            steps {
                input(
                    message: "Plan is okay. Do you want to continue or cancel?",
                    ok: "Approve",
                    submitter: "vs-admin"
                )
            }
        }
    }

    // post 
    post{
        always {
            echo "it is running if you got success means it is working else it is not working"
        }
        success {
            echo "it is working bro...!"
            
        }
        failure {
            echo "it is not working...!"
        }
    }

}
