pipeline {
    agent {
        label AGENT-1
    }
    stages{
        stage('build'){
            steps{
               echo "Building....!"
            }
        }

        stage('testing'){
            steps{
                echo "Testing...!"
            }
        }
    }

    post {
        success{
            echo "success..!"
        }
        failure{
            echo "failure...!"
        }
        always{
            echo "this is roboshop-project"
        }
    }

}