pipeline {
    agent { label 'AGENT-1' }

    options {
        timeout(time: 30, unit: 'MINUTES') // Pipeline will time out after 30 min
        retry(1)
        disableConcurrentBuilds()
        timestamps() 
    }
    environment {
        appVersion = ''
        ACC_ID = "741448928336"
        REGION = "us-east-1"
        PROJECT = "roboshop"
        COMPONENT = "catalogue"
    }

    stages {
        stage('Reading package.json ') {
            steps {
                script {
                    dir('Jenkins-roboshop/catalogue') {
                        echo "Building....!"
                        // Read package.json to get version
                        def packageJson = readJSON file: 'package.json'
                        appVersion = packageJson.version
                        echo "Package version: ${appVersion}"
                        
                        sh """
                            npm install
                        """
                    }
                }
            }
        }

        stage('Docker image Build') {
            steps {
                script {     
                    withAWS(credentials: 'AWS-VICKY-CRED', region: 'us-east-1') {
                        sh """
                            echo "Building Docker Image...pushing to ECR "
                            aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACC_ID}.dkr.ecr.${REGION}.amazonaws.com
                            docker build -t ${ACC_ID}.dkr.ecr.${REGION}.amazonaws.com/${PROJECT}/${COMPONENT}:${appVersion} .
                            docker push ${ACC_ID}.dkr.ecr.${REGION}.amazonaws.com/${PROJECT}/${COMPONENT}:${appVersion}
                        """
                    }
                }
            }
        }
    }

    post {
        success {
            echo "Success..!"
        }
        failure {
            echo "Failure...!"
        }
        always {
            echo "This is roboshop-project"
        }
    }
}
